BWIN = {
    'GETAFE':'GETAFE CF',                
    'LEVANTE':'LEVANTE UD',
    'BETIS':'REAL BETIS',
    'REAL MADRID':'REAL MADRID',
    'ESPANOL':'RCD ESPANYOL BARCELONA',
    'ATH MADRID':'ATLETICO MADRID',
    'SOCIEDAD':'REAL SOCIEDAD',
    'VALLECANO':'RAYO VALLECANO',
    'GRANADA':'GRANADA CF',
    'ATH BILBAO':'ATHLETIC BILBAO',
    'CADIZ':'CADIZ CF',
    'MALLORCA':'RCD MALLORCA',
    'VILLARREAL':'VILLARREAL CF',
    'VALENCIA':'VALENCIA CF',
    'BARCELONA':'FC BARCELONA',
    'ELCHE':'ELCHE CF',
    'SEVILLA':'SEVILLA FC',
    'CELTA':'RC CELTA DE VIGO',
    'ALAVES':'DEPORTIVO ALAVES',
    'OSASUNA':'CA OSASUNA'
}

WILLIAM = {
    'GETAFE':'GETAFE', 
    'LEVANTE':'LEVANTE',
    'BETIS':'REAL BETIS',
    'REAL MADRID':'REAL MADRID',
    'ESPANOL':'ESPANYOL',
    'ATH MADRID':'ATLETICO MADRID',
    'SOCIEDAD':'REAL SOCIEDAD',
    'VALLECANO':'RAYO VALLECANO',
    'GRANADA':'GRANADA',
    'ATH BILBAO':'ATHLETIC CLUB',
    'CADIZ':'CADIZ',
    'MALLORCA':'MALLORCA',
    'VILLARREAL':'VILLARREAL',
    'VALENCIA':'VALENCIA',
    'BARCELONA':'BARCELONA',
    'ELCHE':'ELCHE',
    'SEVILLA':'SEVILLA',
    'CELTA':'CELTA',
    'ALAVES':'ALAVES',
    'OSASUNA':'OSASUNA'
}

POKER = {
    'GETAFE':'GETAFE', 
    'LEVANTE':'LEVANTE',
    'BETIS':'REAL BETIS',
    'REAL MADRID':'REAL MADRID',
    'ESPANOL':'RCD ESPANYOL',
    'ATH MADRID':'ATLETICO DE MADRID',
    'SOCIEDAD':'REAL SOCIEDAD',
    'VALLECANO':'RAYO VALLECANO',
    'GRANADA':'GRANADA',
    'ATH BILBAO':'ATHLETIC DE CLUB',
    'CADIZ':'CADIZ CF',
    'MALLORCA':'RCD MALLORCA',
    'VILLARREAL':'VILLARREAL',
    'VALENCIA':'VALENCIA',
    'BARCELONA':'BARCELONA',
    'ELCHE':'ELCHE CF',
    'SEVILLA':'SEVILLA',
    'CELTA':'CELTA DE VIGO',
    'ALAVES':'ALAVES',
    'OSASUNA':'OSASUNA'
}

BWIN_URL= 'https://sports.bwin.es/es/sports/f%C3%BAtbol-4/apuestas/espa%C3%B1a-28/laliga-102829'
WILLIAM_URL = 'https://sports.williamhill.es/betting/es-es/football/competitions/OB_TY338/Espana-LaLiga-Santander/matches/OB_MGMB/Ganador-del-partido'
POKER_URL = 'https://www.pokerstarssports.es/#/soccer/competitions/10679937'